apiVersion: v1
kind: Service
metadata:
  name: app-deployment-service
  namespace: app-deployment
  labels:
    app: helloword-app
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort:30301
  selector:
    app: helloword-app
  type: LoadBalancer