apiVersion: v1
kind: Service
metadata:
    name: app-deployment-service
    namespace: app-deployment
  labels:
    app: helloword-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloword-app
  type: LoadBalancer