apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword-deployment
  namespace: app-deployment
  labels:
    app: helloword-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloword-app
  template:
    metadata:
      labels:
        app: helloword-app
    spec:
      containers:
      - name: helloword-app-container
        image: 058264125787.dkr.ecr.us-east-1.amazonaws.com/helloword:latest
        imagePullPolicy: Always
        ports:
          - name: helloword-app
            containerPort: 5000
      imagePullSecrets:
          - name: regcred